spring:
  application:
    name: oauth-server
  datasource:
    url: jdbc:mysql://115.29.32.62:3306/ec2?useUnicode=true&characterEncoding=utf8
    username: root
    password: 7d428bc667
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8883
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/
